import edge_tts
import asyncio
import os

async def generate_voice(text, output_file, voice="en-US-ChristopherNeural"):
    communicate = edge_tts.Communicate(text, voice)
    await communicate.save(output_file)

def create_audio_files(script_data, project_id):
    audio_paths = []
    output_dir = f"static/output/{project_id}/audio"
    os.makedirs(output_dir, exist_ok=True)

    print(f"Generating audio for Project {project_id}...")

    async def process_batch():
        tasks = []
        for i, scene in enumerate(script_data):
            text = scene['audio_text']
            filename = os.path.join(output_dir, f"scene_{i}.mp3")
            audio_paths.append(filename)

            tasks.append(generate_voice(text, filename))
        
        await asyncio.gather(*tasks)
    
    asyncio.run(process_batch())
    print(f"Generated {len(audio_paths)} audio clips")
    return audio_paths

#Quick test
if __name__ == "__main__":
    test_script = [
        {"audio_text": "Welcome to the future of AI video generation."},
        {"audio_text": "This voice is generated by Microsoft Edge completely for free."}
    ]
    create_audio_files(test_script, "test_001")