import os
import json
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# Scopes needed for uploading
SCOPES = ["https://www.googleapis.com/auth/youtube.upload"]

def upload_to_youtube(video_path, metadata):
    client_secret_file = "client_secret.json"
    
    # Check if user set up the API (Skip if they didn't)
    if not os.path.exists(client_secret_file):
        print("⚠️ client_secret.json not found. Skipping YouTube upload.")
        return None

    try:
        # Authenticate
        flow = InstalledAppFlow.from_client_secrets_file(client_secret_file, SCOPES)
        credentials = flow.run_local_server(port=0)
        
        youtube = build("youtube", "v3", credentials=credentials)
        
        request_body = {
            "snippet": {
                "title": metadata.get("title", "New AI Video"),
                "description": metadata.get("description", "Generated by AstroNova AI"),
                "tags": metadata.get("tags", []),
                "categoryId": "28"
            },
            "status": {
                "privacyStatus": "unlisted", 
                "selfDeclaredMadeForKids": False
            }
        }
        
        media = MediaFileUpload(video_path, chunksize=-1, resumable=True)
        
        print("🚀 Uploading to YouTube...")
        request = youtube.videos().insert(
            part="snippet,status",
            body=request_body,
            media_body=media
        )
        
        response = request.execute()
        video_id = response.get("id")
        print(f"✅ Upload Complete! Video ID: {video_id}")
        
        return f"https://youtu.be/{video_id}"

    except Exception as e:
        print(f"❌ YouTube Upload Error: {e}")
        return None